project:
  name: "Web Development Project - 50 Tasks"
  total_tasks: 50
  simulation_runs: 10000
  confidence_levels: [0.5, 0.75, 0.90, 0.95]

task_categories:
  Setup:
    count: 1
    complexity_weight: 1.0
  Planning:
    count: 1
    complexity_weight: 1.2
  Frontend:
    count: 8
    complexity_weight: 1.2
  Backend:
    count: 12
    complexity_weight: 1.5
  QA:
    count: 12
    complexity_weight: 1.3
  DevOps:
    count: 8
    complexity_weight: 1.8
  Documentation:
    count: 3
    complexity_weight: 1.0
  Training:
    count: 1
    complexity_weight: 1.1
  Support:
    count: 1
    complexity_weight: 1.2
  Management:
    count: 1
    complexity_weight: 1.0
  Deployment:
    count: 2
    complexity_weight: 2.0

historical_data:
  project_count: 20
  variance_factor: 0.3
  optimism_bias: 1.25

output:
  charts: true
  detailed_report: true
  summary_stats: true
